version: '3'

services:
  aksanhealth.com.tr:
    container_name: aksanhealth.com.tr
    image: aksanhealth.com.tr
    build:
      context: .
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internal
networks:
  internal:
    driver: bridge
